baseURL = 'https://bradparbs.com/'
defaultContentLanguage = 'en'
enableEmoji = true
languageCode = 'en-us'
theme = ["hugo-social-metadata", "pico"]
paginate = 10
title = 'Brad Parbs'
description = "Brad Parbs - Milwaukee WordPress developer."
email = "brad@bradparbs.com"
favicon = '/favicon.png'
enableRobotsTXT = true

[params]
customCSS = ["css/style.css"]
# customJS = ["js/console.js"]
keywords = "brad parbs, bradparbs"
twitterUsername = "@bradparbs"
socialImage = "images/brad-parbs.jpg"

[[params.social]]
alt = "github icon"
blank = true
icon = "/icons/github.svg"
name = "github"
url = "https://github.com/bradp"

[[params.social]]
alt = "twitter icon"
blank = true
icon = "/icons/twitter.svg"
name = "twitter"
url = "https://twitter.com/bradparbs"

[[params.social]]
alt = "linkedin icon"
blank = true
icon = "/icons/linkedin.svg"
name = "linkedin"
url = "https://linkedin.com/in/bradparbs"

[[params.social]]
alt = "email icon"
icon = "/icons/email.svg"
name = "email"
url = "mailto:brad@bradparbs.com"


# Navigation bar
[menu]

[[menu.main]]
identifier = "home"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "projects"
url = "/projects/"
weight = 30

[[menu.main]]
identifier = "blog"
url = "/posts/"
weight = 40

[[menu.main]]
identifier = "contact"
url = "/contact/"
weight = 50

# Syntax highlightning
[markup.highlight]
guessSyntax = true
lineNumbersInTable = true
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
"posts" = "/:year/:title/"

[markup]
  defaultMarkdownHandler = "blackfriday"
