baseURL = 'https://bradparbs.com/'
defaultContentLanguage = 'en'
enableEmoji = true
languageCode = 'en-us'
theme = ["hugo-social-metadata", "pico"]
paginate = 10
title = 'Brad Parbs'
description = "Brad Parbs - Milwaukee WordPress developer."
email = "brad@bradparbs.com"
favicon = '/favicon.png'

[params]
customCSS = ["css/style.css"]
# customJS = ["js/console.js"]
keywords = "brad parbs, bradparbs"
twitterUsername = "@bradparbs"
socialImage = "images/brad-parbs.jpgs"


[[params.social]]
alt = "github icon"
blank = true
icon = "/icons/github.svg"
name = "github"
url = "https://github.com/"

[[params.social]]
alt = "twitter icon"
blank = true
icon = "/icons/twitter.svg"
name = "twitter"
url = "https://twitter.com/"

[[params.social]]
alt = "linkedin icon"
blank = true
icon = "/icons/linkedin.svg"
name = "linkedin"
url = "https://linkedin.com/in/bradparbs"

[[params.social]]
alt = "email icon"
icon = "/icons/email.svg"
name = "email"
url = "mailto:mail@example.com"


# Navigation bar
[menu]

[[menu.main]]
identifier = "home" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/"
weight = 10

[[menu.main]]
identifier = "about" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/about/"
weight = 20

[[menu.main]]
identifier = "projects" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/projects/"
weight = 30

[[menu.main]]
identifier = "contact" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/contact/"
weight = 40

# Syntax highlightning
[markup.highlight]
guessSyntax = true
lineNumbersInTable = true
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
"posts" = "/:year/:title/"
