# Site Details
title = 'Brad Parbs'
description = "Brad Parbs - Milwaukee WordPress developer."
email = "brad@bradparbs.com"
baseURL = 'https://bradparbs.com/'
favicon = '/favicon.png'

[params]
# Used for Open Graph tags & Twitter card tags.
title = 'Brad Parbs'
description = "Brad Parbs - Milwaukee WordPress developer."
images = ["images/share-image.png"]
# Language
languageCode = "en-us"
DefaultContentLanguage = "en"
# Build
canonifyUrls = true
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true
disableFastRender = true
# Content
disableKinds = ["taxonomy", "term"]
enableEmoji = true
enableInlineShortcodes = true
summaryLength = 50

[permalinks]
posts = "/blog/:year/:month/:title/"

[imaging]
resampleFilter = 'Lanczos'
quality = 85

[imaging.exif]
includeFields = ""
disableDate = true
disableLatLong = true

[build]
writeStats = true

[social]
twitter = "bradparbs"

[Author]
name = "Brad Parbs"

[menu]

[[menu.main]]
name = "about"
url = "/about/"
weight = 20

[[menu.main]]
name = "projects"
url = "/projects/"
weight = 30

[[menu.main]]
name = "contact"
url = "/contact/"
weight = 50
